name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Test mypkg
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/mypkg/     # 复制当前 repo 到 ROS workspace 下
          cd /root/ros2_ws
          . /opt/ros/humble/setup.bash         # 或根据实际情况设置
          colcon build
          . install/setup.bash
          bash -xv src/mypkg/test/test.bash /root   # 调用测试脚本（视你 test.bash 内容）